language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
services:
  - docker
before_install:
  - pip install --upgrade pip
  - docker pull xcgd/libreoffice:5.1
  - docker pull xcgd/libreoffice:latest
python:
  - "2.7"
matrix:
  fast_finish: true
install:
  - sudo apt update -qq -y
  - sudo apt install -qq -y libfreetype6-dev liblcms2-dev make libreoffice libreoffice-script-provider-python
  - sudo apt autoremove -qq -y
  - sudo apt autoclean -qq -y
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
  - docker run -p 127.0.0.1:2002:8997 -d --rm --name="oo_server" xcgd/libreoffice:5.1
  - bin/translation-manage -c
  - firefox -v
script:
  - docker ps
  - env USE_STREAM=True bin/test
  - docker stop oo_server
  - docker run -p 127.0.0.1:2002:8997 -d --rm --name="oo_server" xcgd/libreoffice:latest
  - docker ps
  - env USE_STREAM=True bin/test
  - docker stop oo_server
  - /usr/bin/soffice --invisible --headless --nologo --nofirststartwizard --accept="socket,host=localhost,port=2002;urp" & > /dev/null 2>&1
  - env USE_STREAM=False bin/test
  - env USE_STREAM=True bin/test
after_success:
  - bin/createcoverage -d htmlcov
  - pip install --upgrade pip
  - pip install -q coveralls==0.5
  - coveralls
