# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      libreoffice:
        image: xcgd/libreoffice:latest
        ports:
          - 2002:8997
        volumes:
          - /tmp:/tmp
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 2
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Setup Env
        run: |
          mkdir -p -m 777 /tmp/appy/
          sudo apt update -qq -y
          sudo apt-get install -qq -y libfreetype6-dev liblcms2-dev libreoffice libreoffice-script-provider-python
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ./buildout-cache/eggs ./eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: buildout
        run: |
          pip install -r requirements.txt coverage==5.3.1
          buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
          buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
      - name: test
        run: |
          docker ps -a
          bin/test
  coverage:
    runs-on: ubuntu-18.04
    services:
      libreoffice:
        image: xcgd/libreoffice:latest
        ports:
          - 2002:8997
        volumes:
          - /tmp:/tmp
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 2
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Setup Env
        run: |
          mkdir -p -m 777 /tmp/appy/
          sudo apt update -qq -y
          sudo apt-get install -qq -y libfreetype6-dev liblcms2-dev libreoffice libreoffice-script-provider-python
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ./eggs ./eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: buildout
        run: |
          pip install -r requirements.txt coverage==5.3.1
          buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
          buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
      - name: test coverage
        run: |
          docker ps -a
          bin/coverage run bin/test
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Coveralls
        run: |
          pip3 install -U pip setuptools --no-cache-dir
          pip3 install -U "coveralls>=3.0.0" coverage==5.3.1 --no-cache-dir
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
