# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      libreoffice:
        image: xcgd/libreoffice:latest
        ports:
          - 2002:8997
        volumes:
          - /tmp:/tmp
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v14"
        with:
          default: 2.7.18
          versions: 3.8.16
          command: pyenv -v
      - name: Setup Env
        run: |
          mkdir -p -m 777 /tmp/appy/
          sudo apt update -qq -y
          sudo apt-get install -qq -y libfreetype6-dev liblcms2-dev libreoffice libreoffice-script-provider-python
      - name: Cache eggs
        uses: actions/cache@v4
        env:
          cache-name: cache-eggs
        with:
          path: ~/.buildout/eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: buildout
        run: |
          pip install -r requirements.txt coverage==5.3.1
          buildout -c ci.cfg annotate
          buildout -c ci.cfg
      - name: test
        run: |
          docker ps -a
          bin/test
  coverage:
    runs-on: ubuntu-latest
    services:
      libreoffice:
        image: xcgd/libreoffice:latest
        ports:
          - 2002:8997
        volumes:
          - /tmp:/tmp
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up pyenv and Python
        uses: "gabrielfalcao/pyenv-action@v14"
        with:
          default: 2.7.18
          versions: 3.8.16
          command: pyenv -v
      - name: Setup Env
        run: |
          mkdir -p -m 777 /tmp/appy/
          sudo apt update -qq -y
          sudo apt-get install -qq -y libfreetype6-dev liblcms2-dev libreoffice libreoffice-script-provider-python
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ~/.buildout/eggs
          key: ${{ runner.os }}-build-coverage-${{ env.cache-name }}
      - name: buildout
        run: |
          pip install -r requirements.txt coverage==5.3.1
          buildout -c ci.cfg annotate
          buildout -c ci.cfg
      - name: code-analysis
        run: |
          bin/code-analysis
      - name: test coverage
        run: |
          docker ps -a
          bin/coverage run bin/test
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Coveralls
        run: |
          pip3 install -U pip setuptools --no-cache-dir
          pip3 install -U "coveralls>=3.0.0" coverage==5.3.1 --no-cache-dir
      - name: Publish to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
